-- Daily position health signals generated by the trade-doctor cron.
-- Dismissed by the user; regenerated fresh each day.
CREATE TABLE position_alerts (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
  ticker           text NOT NULL,
  alert_type       text NOT NULL CHECK (alert_type IN (
                     'stop_proximity', 'r_target_reached', 'earnings_risk',
                     'concentration_high', 'streak_caution'
                   )),
  severity         text NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  message          text NOT NULL,
  why              text NOT NULL,
  suggested_review text NOT NULL,
  generated_at     timestamptz NOT NULL DEFAULT now(),
  dismissed_at     timestamptz
);

ALTER TABLE position_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner" ON position_alerts
  USING (auth.uid() = user_id);

CREATE INDEX ON position_alerts(user_id, generated_at DESC);
