import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getUserAndProfile, DEFAULT_PROFILE } from "@/lib/profile";
import { getHoldingsView } from "@/lib/portfolio";
import { AiChat } from "./_components/ai-chat";

export const dynamic = "force-dynamic";
export const metadata = { title: "AI helper · TradePilot" };

export default async function AiPage() {
  const supabase = await createSupabaseServerClient();
  if (!supabase) redirect("/login");

  const session = await getUserAndProfile();
  if (!session) redirect("/login");

  const { profile } = session;
  const accountSize =
    profile.account_size_initial ?? DEFAULT_PROFILE.account_size_initial;
  const maxRiskPct =
    profile.max_risk_per_trade_pct ?? DEFAULT_PROFILE.max_risk_per_trade_pct;
  const dailyLossLimitPct =
    profile.daily_loss_limit_pct ?? DEFAULT_PROFILE.daily_loss_limit_pct;

  const holdings = await getHoldingsView();

  // Budget usage this month
  const startOfMonth = new Date();
  startOfMonth.setDate(1);
  startOfMonth.setHours(0, 0, 0, 0);

  const { data: usageRows } = await supabase
    .from("ai_notes")
    .select("input_tokens, output_tokens")
    .gte("created_at", startOfMonth.toISOString());

  const usedTokens = (usageRows ?? []).reduce(
    (sum, r) => sum + ((r.input_tokens as number) ?? 0) + ((r.output_tokens as number) ?? 0),
    0,
  );
  const budget = (profile.ai_token_budget_monthly as number | null) ?? 100_000;
  const budgetPct = Math.min(100, Math.round((usedTokens / budget) * 100));

  const portfolioContext = {
    accountSize,
    maxRiskPct,
    dailyLossLimitPct,
    totalMarketValue: holdings.total_market_value,
    totalOpenPnl: holdings.total_open_pnl,
    holdings: holdings.holdings.map((h) => ({
      ticker: h.ticker,
      qty: h.qty,
      avgCost: h.avg_cost,
      price: h.price,
      openPnl: h.open_pnl,
      marketValue: h.market_value,
    })),
  };

  return (
    <div className="mx-auto max-w-3xl space-y-8 px-6 py-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-lg font-semibold tracking-tight">AI helper</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Ask about my portfolio, risk, watchlist scores, or journal patterns.
          </p>
        </div>
        <div className="text-right shrink-0">
          <p className="text-xs text-muted-foreground tabular-nums">
            {usedTokens.toLocaleString()} / {budget.toLocaleString()} tokens this month
          </p>
          <div className="mt-1 h-1 w-32 rounded-full bg-foreground/10 overflow-hidden ml-auto">
            <div
              className={`h-full rounded-full ${budgetPct >= 90 ? "bg-red-400" : budgetPct >= 70 ? "bg-yellow-400" : "bg-foreground/40"}`}
              style={{ width: `${budgetPct}%` }}
            />
          </div>
        </div>
      </div>

      <AiChat portfolioContext={portfolioContext} />

      <p className="text-[11px] text-muted-foreground/60 border-t border-border/30 pt-4">
        Educational and decision-support only. Not financial advice. Markets involve risk.
        Responses are generated by claude-sonnet-4-6 and logged for your review. Token costs are shown per response.
      </p>
    </div>
  );
}
